import type { Metadata } from "next";

import "../../globals.css";

import NavBar from "@/components/navBar";

export const metadata: Metadata = {
  title: "Agenda",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className="antialiased">
        <div className="bg-[#ffe7c7] h-screen flex flex-row text-[#43553b]">
          <NavBar />
          <div className={`flex flex-col w-full overflow-y-auto `}>
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
