import type { Metadata } from "next";
import { Poppins } from "next/font/google";
/* import localFont from "next/font/local"; */
import "../../globals.css";

import NavBar from "@/components/navBar";
import TaskBar from "@/components/taskBar";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-poppins",
});

/* const Titles = localFont({
  src: "../../../public/fonts/MongoDBValueSerif-Regular.woff2",
  variable: "--font-titles",
}); */

export const metadata: Metadata = {
  title: "Clientes",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="bg-[#ffe7c7] h-screen flex flex-row text-[#43553b]">
      <NavBar />
      <div
        className={`${poppins.variable} flex flex-col w-full overflow-y-auto`}
      >
        <TaskBar />
        <div className="h-full">{children}</div>
      </div>
    </div>
  );
}
