import type { Metadata } from "next";
import { Poppins } from "@/utils/fonts";
/* import localFont from "next/font/local"; */
import "../../globals.css";

import NavBar from "@/components/navBar";

export const metadata: Metadata = {
  title: "Insights",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="bg-[#ffe7c7] h-screen flex flex-row text-[#43553b]">
      <NavBar />
      <div
        className={`${Poppins.variable} flex flex-col w-full overflow-y-auto `}
      >
        {children}
      </div>
    </div>
  );
}
