import type { Metadata } from "next";

import "../../globals.css";

import NavBar from "@/components/navBar";

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="bg-[#ffe7c7] h-screen flex flex-row text-[#43553b]">
      <NavBar />
      <div>{children}</div>
    </div>
  );
}
